export const ADMIN_NAV_ITEMS = [
  {
    path: '/dashboard',
    label: '仪表盘',
    hint: 'Overview',
    icon: 'solar:chart-square-outline',
    eyebrow: 'Control Center',
    title: '仪表盘',
    description: '查看系统概况、最近录入内容与核心管理指标。',
  },
  {
    path: '/apps',
    label: '应用管理',
    hint: 'Applications',
    icon: 'solar:widget-5-outline',
    eyebrow: 'Catalog',
    title: '应用管理',
    description: '维护应用目录、链接、图标与关联菜单。',
  },
  {
    path: '/menus',
    label: '菜单管理',
    hint: 'Navigation',
    icon: 'solar:sidebar-code-outline',
    eyebrow: 'Structure',
    title: '菜单管理',
    description: '组织菜单层级，控制信息结构与排序。',
  },
  {
    path: '/settings',
    label: '站点设置',
    hint: 'Settings',
    icon: 'solar:settings-outline',
    eyebrow: 'System',
    title: '站点设置',
    description: '维护站点基础信息、图标与外部服务配置。',
  },
  {
    path: '/admin',
    label: '用户管理',
    hint: 'Access',
    icon: 'solar:users-group-two-rounded-outline',
    eyebrow: 'Permissions',
    title: '用户管理',
    description: '管理后台账号、状态、权限与安全设置。',
  },
];
